require('plugins/themes-cfg')
require('plugins/packer-cfg')
require('plugins/lsp-cfg')
require('plugins/telescope-cfg')
require('plugins/treesitter-cfg')
require('plugins/completion-cfg')
require('plugins/nvim-tree-cfg')
require('plugins/lualine-cfg')
require('plugins/comment-cfg')

